changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - bugfix
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - refactor
    - title: Other Changes
      labels:
        - '*'
